[DEFAULT]
cp-host = <clearpass hostname>
cp-port = 443
cp-user = <API username>
cp-pass = <API password>
filter = '{"$and": [{"mac_address": {"$exists": true}},{"status": {"$eq": "Known"}}]}'
output = <output filename>.json
[API_CLIENT]
client_id = <Clearpass API client ID>
client_secret = <Clearpass AP client secret>
grant_type=client_credentials
limit=1000

# Filter syntax examples
# filter = '{"$and": [{"mac_address": {"$exists": true}},{"status": {"$eq": "Known"}}]}'
# filter = '{"$or": [{"$and": [{"mac_address": {"$exists": true}},{"status": {"$eq": "Known"}}]},{"profile": {"$exists": true}}]}'
# filter = '{"device_insight_tags": ["[Computers & Servers]","[Networking & Switching]","[Printers]"]}'
# filter = '{"profile.device_category": {"$contains": "Printer"}}'