[DEFAULT]
cp-host = clearpass1.selectium.local
cp-port = 443
cp-user = pyclearpass
cp-pass = 
#filter = '{"$or": [{"$and": [{"mac_address": {"$exists": true}},{"status": {"$eq": "Known"}}]},
#                  {"profile": {"$exists": true}}
#                  ]
#       }'
#filter = '{"status": {"$exists": true}}'
filter = '{"$and": [{"mac_address": {"$exists": true}},{"status": {"$eq": "Known"}}]}'

output = test_endpoint_2.json
[API_CLIENT]
client_id = endpoint_client
client_secret = UzAhE6x0WGlyib+NjJUrlMpAaNZQX0DdCDNHK1lWxdZU
grant_type=client_credentials
limit=1000

# Filter syntax examples
# filter = '{"$and": [{"mac_address": {"$exists": true}},{"status": {"$eq": "Known"}}]}'
# filter = '{"$or": [{"$and": [{"mac_address": {"$exists": true}},{"status": {"$eq": "Known"}}]},{"profile": {"$exists": true}}]}'
# filter = '{"device_insight_tags": ["[Computers & Servers]","[Networking & Switching]","[Printers]"]}'
# filter = '{"profile.device_category": {"$contains": "Printer"}}'